const fs = require('fs');
const path = require('path');
const webpush = require('web-push');
const { getDb, queryAll, queryOne, runSql } = require('./database');
const logger = require('./logger');

let configured = false;
let autoGenerated = false;

function vapidStorePath() {
  const dbPath = process.env.DB_PATH
    ? path.resolve(process.env.DB_PATH)
    : path.resolve(__dirname, 'terrainsn.db');
  return path.join(path.dirname(dbPath), 'vapid-keys.json');
}

function loadPersistedVapid() {
  try {
    const file = vapidStorePath();
    if (!fs.existsSync(file)) return null;
    const raw = JSON.parse(fs.readFileSync(file, 'utf8'));
    if (raw?.publicKey && raw?.privateKey) return raw;
  } catch {
    /* ignore */
  }
  return null;
}

function persistVapid(keys) {
  try {
    const file = vapidStorePath();
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(
      file,
      JSON.stringify(
        {
          publicKey: keys.publicKey,
          privateKey: keys.privateKey,
          subject: keys.subject || process.env.VAPID_SUBJECT || 'mailto:contact@terrainsn.com',
          generatedAt: new Date().toISOString(),
        },
        null,
        2,
      ),
      'utf8',
    );
    return true;
  } catch (err) {
    logger.warn('pushService', `Impossible de persister VAPID : ${err.message}`);
    return false;
  }
}

/**
 * Résout les clés VAPID : env → fichier à côté de la DB → génération auto (persistée).
 * Sur Render free sans disque, la génération se répète à chaque machine neuve
 * (les abonnements push devront être re-souscrits) — préférer les env vars.
 */
function resolveVapidKeys() {
  let publicKey = String(process.env.VAPID_PUBLIC_KEY || '').trim();
  let privateKey = String(process.env.VAPID_PRIVATE_KEY || '').trim();
  const subject = process.env.VAPID_SUBJECT || 'mailto:contact@terrainsn.com';

  if (publicKey && privateKey) {
    return { publicKey, privateKey, subject, source: 'env' };
  }

  const stored = loadPersistedVapid();
  if (stored) {
    process.env.VAPID_PUBLIC_KEY = stored.publicKey;
    process.env.VAPID_PRIVATE_KEY = stored.privateKey;
    if (stored.subject && !process.env.VAPID_SUBJECT) {
      process.env.VAPID_SUBJECT = stored.subject;
    }
    return {
      publicKey: stored.publicKey,
      privateKey: stored.privateKey,
      subject: stored.subject || subject,
      source: 'file',
    };
  }

  const generated = webpush.generateVAPIDKeys();
  process.env.VAPID_PUBLIC_KEY = generated.publicKey;
  process.env.VAPID_PRIVATE_KEY = generated.privateKey;
  const persisted = persistVapid({ ...generated, subject });
  autoGenerated = true;
  logger.warn(
    'pushService',
    persisted
      ? 'VAPID auto-générées et persistées près de la DB — ajoutez-les en env Render pour stabilité multi-machine'
      : 'VAPID auto-générées en mémoire seule — les push seront invalidés au redémarrage',
  );
  return {
    publicKey: generated.publicKey,
    privateKey: generated.privateKey,
    subject,
    source: persisted ? 'generated-persisted' : 'generated-memory',
  };
}

function getVapidConfig() {
  const keys = resolveVapidKeys();
  return {
    publicKey: keys.publicKey || '',
    privateKey: keys.privateKey || '',
    subject: keys.subject || 'mailto:contact@terrainsn.com',
    source: keys.source,
    autoGenerated,
  };
}

function ensureConfigured() {
  if (configured) return true;
  const { publicKey, privateKey, subject } = getVapidConfig();
  if (!publicKey || !privateKey) {
    logger.warn('pushService', 'VAPID keys manquantes — Web Push desactivé');
    return false;
  }
  webpush.setVapidDetails(subject, publicKey, privateKey);
  configured = true;
  return true;
}

function getPublicKey() {
  ensureConfigured();
  return getVapidConfig().publicKey || null;
}

function describe() {
  const cfg = getVapidConfig();
  const ok = Boolean(cfg.publicKey && cfg.privateKey);
  return {
    configured: ok,
    source: cfg.source || null,
    autoGenerated,
    subject: cfg.subject,
    readyForProd: ok && (cfg.source === 'env' || cfg.source === 'file'),
  };
}

async function upsertSubscription(userId, subscription, userAgent = '') {
  ensureConfigured();
  const db = await getDb();
  const { endpoint, keys } = subscription;
  if (!endpoint || !keys?.p256dh || !keys?.auth) {
    throw new Error('Subscription Web Push invalide');
  }

  runSql(db, `INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
    VALUES (?, ?, ?, ?, ?)
    ON CONFLICT(endpoint) DO UPDATE SET
      user_id = excluded.user_id,
      p256dh = excluded.p256dh,
      auth = excluded.auth,
      user_agent = excluded.user_agent`, [
    userId,
    endpoint,
    keys.p256dh,
    keys.auth,
    userAgent.slice(0, 255),
  ]);

  runSql(db, `INSERT OR IGNORE INTO push_preferences (user_id) VALUES (?)`, [userId]);
}

async function removeSubscription(userId, endpoint) {
  const db = await getDb();
  runSql(db, 'DELETE FROM push_subscriptions WHERE user_id = ? AND endpoint = ?', [userId, endpoint]);
}

async function getPreferences(userId) {
  const db = await getDb();
  const prefs = queryOne(db, 'SELECT * FROM push_preferences WHERE user_id = ?', [userId]);
  if (!prefs) {
    return {
      reservation_confirmation: true,
      rappel_reservation: true,
      promotion: false,
      nouveau_message: true,
      avis_reponse: true,
    };
  }
  return {
    reservation_confirmation: !!prefs.reservation_confirmation,
    rappel_reservation: !!prefs.rappel_reservation,
    promotion: !!prefs.promotion,
    nouveau_message: !!prefs.nouveau_message,
    avis_reponse: !!prefs.avis_reponse,
  };
}

async function updatePreferences(userId, prefs) {
  const db = await getDb();
  runSql(db, `INSERT INTO push_preferences (user_id, reservation_confirmation, rappel_reservation, promotion, nouveau_message, avis_reponse)
    VALUES (?, ?, ?, ?, ?, ?)
    ON CONFLICT(user_id) DO UPDATE SET
      reservation_confirmation = excluded.reservation_confirmation,
      rappel_reservation = excluded.rappel_reservation,
      promotion = excluded.promotion,
      nouveau_message = excluded.nouveau_message,
      avis_reponse = excluded.avis_reponse`, [
    userId,
    prefs.reservation_confirmation ? 1 : 0,
    prefs.rappel_reservation ? 1 : 0,
    prefs.promotion ? 1 : 0,
    prefs.nouveau_message ? 1 : 0,
    prefs.avis_reponse ? 1 : 0,
  ]);
  return getPreferences(userId);
}

async function getSubscriptionsForUser(userId) {
  const db = await getDb();
  return queryAll(db, 'SELECT * FROM push_subscriptions WHERE user_id = ?', [userId]);
}

async function sendToUser(userId, payload, preferenceKey = null) {
  if (!ensureConfigured()) return { sent: 0, failed: 0 };

  if (preferenceKey) {
    const prefs = await getPreferences(userId);
    if (!prefs[preferenceKey]) return { sent: 0, failed: 0, skipped: true };
  }

  const subscriptions = await getSubscriptionsForUser(userId);
  let sent = 0;
  let failed = 0;

  for (const sub of subscriptions) {
    try {
      await webpush.sendNotification(
        {
          endpoint: sub.endpoint,
          keys: { p256dh: sub.p256dh, auth: sub.auth },
        },
        JSON.stringify(payload),
      );
      sent++;
    } catch (err) {
      failed++;
      if (err.statusCode === 404 || err.statusCode === 410) {
        const db = await getDb();
        runSql(db, 'DELETE FROM push_subscriptions WHERE id = ?', [sub.id]);
      }
      logger.error('pushService', `Envoi push echoue (user ${userId})`, err);
    }
  }

  return { sent, failed };
}

async function envoyerConfirmationPush(reservationId) {
  const db = await getDb();
  const reservation = queryOne(db, `SELECT r.*, t.nom AS terrain_nom
    FROM reservations r JOIN terrains t ON t.id = r.terrain_id WHERE r.id = ?`, [reservationId]);
  if (!reservation?.joueur_id) return;

  await sendToUser(reservation.joueur_id, {
    title: 'Réservation confirmée ⚽',
    body: `${reservation.terrain_nom} — ${reservation.date} à ${reservation.heure_debut}. Code : ${reservation.code_reservation || 'N/A'}`,
    url: '/reservations',
    tag: `reservation-${reservationId}`,
    type: 'reservation_confirmation',
  }, 'reservation_confirmation');

  runSql(db, `INSERT INTO notifications (destinataire_type, destinataire_id, type, canal, contenu, lu)
    VALUES ('user', ?, 'confirmation', 'push', ?, 0)`, [
    reservation.joueur_id,
    `Réservation confirmée : ${reservation.terrain_nom} le ${reservation.date} à ${reservation.heure_debut}`,
  ]);
}

function parseReservationDateTime(dateStr, timeStr) {
  const date = String(dateStr).slice(0, 10);
  const time = String(timeStr).slice(0, 5);
  return new Date(`${date}T${time}:00`);
}

async function envoyerRappelsReservations() {
  if (!ensureConfigured()) return { processed: 0 };

  const db = await getDb();
  const now = new Date();
  const windowStart = new Date(now.getTime() + 45 * 60 * 1000);
  const windowEnd = new Date(now.getTime() + 75 * 60 * 1000);

  const reservations = queryAll(db, `
    SELECT r.*, t.nom AS terrain_nom
    FROM reservations r
    JOIN terrains t ON t.id = r.terrain_id
    LEFT JOIN reservation_reminders rr ON rr.reservation_id = r.id
    WHERE r.statut IN ('confirme', 'acceptee')
      AND r.joueur_id IS NOT NULL
      AND rr.id IS NULL
      AND r.date >= date('now')
  `);

  let processed = 0;

  for (const reservation of reservations) {
    const startAt = parseReservationDateTime(reservation.date, reservation.heure_debut);
    if (Number.isNaN(startAt.getTime())) continue;
    if (startAt < windowStart || startAt > windowEnd) continue;

    const prefs = await getPreferences(reservation.joueur_id);
    if (!prefs.rappel_reservation) continue;

    const result = await sendToUser(reservation.joueur_id, {
      title: 'Rappel — match dans 1h ⏰',
      body: `${reservation.terrain_nom} — ${reservation.date} à ${reservation.heure_debut}. Préparez-vous !`,
      url: '/reservations',
      tag: `reminder-${reservation.id}`,
      type: 'rappel_reservation',
    }, 'rappel_reservation');

    if (result.sent > 0) {
      runSql(db, 'INSERT INTO reservation_reminders (reservation_id) VALUES (?)', [reservation.id]);
      runSql(db, `INSERT INTO notifications (destinataire_type, destinataire_id, type, canal, contenu, lu)
        VALUES ('user', ?, 'rappel', 'push', ?, 0)`, [
        reservation.joueur_id,
        `Rappel : match au ${reservation.terrain_nom} dans 1h`,
      ]);
      processed++;
    }
  }

  return { processed };
}

module.exports = {
  getPublicKey,
  ensureConfigured,
  describe,
  upsertSubscription,
  removeSubscription,
  getPreferences,
  updatePreferences,
  sendToUser,
  envoyerConfirmationPush,
  envoyerRappelsReservations,
};
